language: python
python:
  - "2.6"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - pip install codecov
  - pip install flake8
# command to install dependencies
install:
  - pip install .

before_script:
  - chmod 777 ./test/do_test.sh
# command to run tests
script: ./test/do_test.sh
after_success:
  - codecov
